
# makefile for gemo works

CC=g++
CFLAGS=-g -Wall
CLASS_PATH=/home/minh/Learning/Courses/Gemo/Lecture/TechnicalModule/Class
RUN_FILE=gemo.pricing.Calculator
all: compile

compile: 
	javac @Configure/options.sh @Configure/sources.sh

run:
	java -cp $(CLASS_PATH) $(RUN_FILE)